<?php
require_once "Cuenta.php";

class CuentaCorriente extends Cuenta
{
    private $cuota_mantenimiento;

    /**
     * CuentaCorriente constructor.
     * @param $cuota_mantenimiento
     */
    public function __construct($numero, $titular, $saldo, $cuota_mantenimiento)
    {
        parent::__construct($numero, $titular, $saldo);
        $this->cuota_mantenimiento = $cuota_mantenimiento;
        $this->saldo-=$this->cuota_mantenimiento;

    }

    /**
     * @return mixed
     */
    public function getCuotaMantenimiento()
    {
        return $this->cuota_mantenimiento;
    }

    /**
     * @param mixed $cuota_mantenimiento
     */
    public function setCuotaMantenimiento($cuota_mantenimiento)
    {
        $this->cuota_mantenimiento = $cuota_mantenimiento;
    }

    public function reintegro($cantidad)
    {
        parent::reintegro($cantidad); // TODO: Change the autogenerated stub
    }


    public function mostrar()
    {
        echo parent::mostrar() . $this->cuota_mantenimiento;

    }
}